server:
  port: 8000

spring:
  boot:
    admin:
      client:
        url: http://localhost:8041
        username: deltaqin
        password: deltaqin
    info:
      app:
        name: ${spring.application.name}
        description: "@project.description@"
        version: "@project.version@"
  rabbitmq:
    host: 134.175.193.18
    username: deltaqin
    password: deltaqin
    virtual-host: /

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

sys:
  sms:
    accessKeyId: LTAI4FjHHtAmP4CpzDqQg7Ld # accessKeyId
    accessKeySecret: ZqSlUllFoC62GbDMgXdGiEX7OIzBiy # AccessKeySecret
    signName: deltaqin # 签名名称
    verifyCodeTemplate: SMS_202546973 # 模板名称

predict:
  sms:
    accessKeyId: LTAI4FjHHtAmP4CpzDqQg7Ld # accessKeyId
    accessKeySecret: ZqSlUllFoC62GbDMgXdGiEX7OIzBiy # AccessKeySecret
    signName: SCUclub # 签名名称
    verifyCodeTemplate: SMS_204735191  # 模板名称
